# Generated by Django 5.0.4 on 2024-05-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_fightingstyles_cat_fighting_styles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fightingstyles',
            name='name',
            field=models.CharField(choices=[('BX', 'Box'), ('KB', 'Kickboxing'), ('MT', 'Muay Thai'), ('WR', 'Wrestling'), ('BJJ', 'Brazilian Jiu-Jitsu')], max_length=50),
        ),
    ]
